version: '3.8'

services:
  pocketbase:
    image: elestio/pocketbase:v0.22.18
    restart: always
    user: 0:0
    ports:
      - 8090:8090
    volumes:
      - ./data:/pb_data
    environment:
      EMAIL: ${POCKETBASE_EMAIL}
      ADMIN_PASSWORD: ${POCKETBASE_ADMIN_PASSWORD}

volumes:
  data:
