version: '3.8'

services:
  api:
    build:
      context: api
      dockerfile: Dockerfile

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  data:
